### ISSUE TITLE
PA Review: Heroku & User Auth

### ISSUE THREAD

**Issue by ashes-ashes** [ashes-ashes/enyo#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
- [ ] Need to clear errors (reproduce: switch between forms after errors have rendered)
- [ ] Add underline to links to illustrate link-ness
- [ ] Adjust session form button width to match field width (optional)
- [ ] Add demo user functionality
- [ ] center align header buttons with logo

**Comment by ryan-mapa** [comment]
Nice job!
